### PR TITLE
adds external login support to dlauthenticator

### PR DESCRIPTION
**Pull request by chaduhduh**

### CODE REVIEW

**Comment by chaduhduh** [comment]
@mjfitzpatrick we may not want to merge this in the way I have it but please have a look. I modified the existing dlauthenticator but it might better to create an additional authenticator file and install it so that we can easily toggle between the two? That way if our new login pages go down or have some major issues we can just update the authenticator setting and don't need to revert code.

**Comment by chaduhduh** [comment]
Also we have defined the `is_auth_token` method, but maybe that can come out of authClient or the utils package? It is probably fine since we just need the username but let me know what you think.

**Review by mjfitzpatrick — APPROVED** [review]

**Comment by mjfitzpatrick** [comment]
I've tagged the initial release as a v1.0.  Given the time crunch, my preference would be to wait until there's less stress and "upgrade" the installed version by using the named branch.  If there's a problem then all we need to do is fallback to the master and reinstall in the dlstack.  When this is ready, we'll do the reverse to run off the branch.

**Comment by chaduhduh** [comment]
Sounds good to me thanks @mjfitzpatrick !

**Comment by mjfitzpatrick** [comment]
Deployed to gp12 running external-login-authenticator branch

**Pull request merged**
